// Chạy tự động khi MongoDB container khởi động lần đầu
// MONGO_INITDB_DATABASE=ecommerce → db đã trỏ đến ecommerce

db.products.insertMany([
  {
    _id: 2001,
    name: 'Dell XPS 15 9530',
    category: 'Laptop',
    brand: 'Dell',
    images: ['https://cdn.example.com/dell-xps15-1.jpg'],
    specs: {
      cpu: 'Intel Core i9-13900H',
      ram: '32GB DDR5',
      ssd: '1TB NVMe PCIe 4.0',
      gpu: 'NVIDIA GeForce RTX 4060 8GB',
      screen: '15.6 inch OLED 3.5K 60Hz',
      battery: '86Wh',
      weight: '1.86kg',
      os: 'Windows 11 Home',
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    _id: 2002,
    name: 'iPhone 15 Pro Max',
    category: 'Smartphone',
    brand: 'Apple',
    images: ['https://cdn.example.com/iphone15pm-1.jpg'],
    specs: {
      chipset: 'Apple A17 Pro',
      screen: '6.7 inch Super Retina XDR OLED',
      battery: '4422mAh',
      camera: '48MP Main + 12MP Ultra Wide + 12MP 5x Telephoto',
      storage_options: ['256GB', '512GB', '1TB'],
      os: 'iOS 17',
      weight: '221g',
      material: 'Titanium',
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    _id: 2003,
    name: 'Sony Alpha A7 IV',
    category: 'Camera',
    brand: 'Sony',
    images: ['https://cdn.example.com/sony-a7iv-1.jpg'],
    specs: {
      sensor: '33MP Full-Frame BSI CMOS',
      iso: '100-51200 (expandable 50-204800)',
      autofocus: '759-point phase-detect AF',
      video: '4K 60p / FHD 120p',
      mount: 'Sony E-mount',
      stabilization: '5-axis in-body',
      weight: '659g',
      weather_sealed: true,
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    _id: 2004,
    name: 'MacBook Pro 14 M3 Pro',
    category: 'Laptop',
    brand: 'Apple',
    images: ['https://cdn.example.com/mbp14-1.jpg'],
    specs: {
      chip: 'Apple M3 Pro (11-core CPU, 14-core GPU)',
      ram: '18GB Unified Memory',
      ssd: '512GB SSD',
      screen: '14.2 inch Liquid Retina XDR 120Hz',
      battery: '70Wh (up to 18h)',
      weight: '1.61kg',
      ports: ['3x Thunderbolt 4', 'HDMI', 'SD card', 'MagSafe 3'],
      os: 'macOS Sonoma',
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    _id: 2005,
    name: 'Samsung Galaxy S24 Ultra',
    category: 'Smartphone',
    brand: 'Samsung',
    images: ['https://cdn.example.com/s24ultra-1.jpg'],
    specs: {
      chipset: 'Snapdragon 8 Gen 3',
      screen: '6.8 inch Dynamic AMOLED 2X 120Hz',
      battery: '5000mAh',
      camera: '200MP Main + 12MP Ultra Wide + 10MP 3x + 50MP 5x',
      storage: '256GB / 512GB / 1TB',
      stylus: 'S Pen included',
      os: 'Android 14 (One UI 6.1)',
      weight: '232g',
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    _id: 2006,
    name: 'Fujifilm X-T5',
    category: 'Camera',
    brand: 'Fujifilm',
    images: ['https://cdn.example.com/xt5-1.jpg'],
    specs: {
      sensor: '40.2MP APS-C X-Trans CMOS 5 HR',
      iso: '125-12800 (expandable 64-51200)',
      autofocus: 'Subject detection AF',
      video: '6.2K 30p / 4K 60p',
      mount: 'Fujifilm X-mount',
      film_simulations: 20,
      weight: '557g',
      weather_sealed: true,
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]);

db.products.createIndex({ category: 1 });
db.products.createIndex({ brand: 1 });
db.products.createIndex({ name: 'text' });
